### ISSUE TITLE
3.1 - c

### ISSUE THREAD

**Issue by daveschafer** [KilnOfTheSecondFlame/STAT_HS18_Exercises#2]
Bei der Aufgabe 3.1, Teilaufgabe c, ist bei deiner Latex Funktion noch ein "...=0 * 9000".
Sieht nach einem Typo aus :)

@tschibu

**Comment by KilnOfTheSecondFlame** [comment]
Sorry für die späte Antwort, musste noch den Kater vom Silvester kurieren 😆 

Dies ist leider ein Problem mit der Rendering Engine von Github. das "0*9000" ist kein Typo sondern eine Konsequenz aus den Umformungen. Die Raw Source zeigt ein klareres Bild:
    "Gesucht ist ein $a$ sodass $P(X>a)=0.1$ also ist $P(X\\leq a)=0.9$, somit muss gelten $F(a)=0.9$. Mit der Formel aus b):\n",
    "\n",
    "$$\\frac{1}{9000}(\\frac{15}{2}a^2-\\frac{1}{12}a^3) = 0.9$$\n",
    "\n",
    "$$\\frac{15}{2}a^2-\\frac{1}{12}a^3 = 0.9\\cdot 9000$$\n",
    "\n",
    "$$\\frac{15}{2}a^2-\\frac{1}{12}a^3 - 8100 = 0\\cdot 9000$$"

Aber ich habe die Rechnung verschönert in 2b6ee8d08dfc7a177f97225fe41441a9bae9c125
